services:
  - type: web
    name: volunteer-app
    env: python
    buildCommand: pip install -r requirements.txt && cd volunteer && python manage.py collectstatic --noinput
    startCommand: cd volunteer && gunicorn volunteer.wsgi:application
