services:
  - type: web
    name: django-demo
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn your_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
